filebeat.inputs:
- type: filestream
  id: lancache
  enabled: true
  paths:
    - /srv/lancache/logs/*.log
    - /srv/lancache/logs/http/*.log
    - /srv/lancache/logs/stream/*.log

filebeat.config.modules:
  reload.enabled: true

output.logstash:
  hosts: ["example.com:5044"]
